### ISSUE TITLE
Firefox?

### ISSUE THREAD

**Issue by Cassian-Andor** [kairi003/Get-cookies.txt-LOCALLY#16]
Would it be very difficult to make this work as a firefox extension? I have no idea how difficult the porting is.
Seeing as this is the only trustable cookie export extension out there after the outrage about you know which other one.

**Comment by kairi003** [comment]
Hello! 
I had not planned to support Firefox, but I will consider it.
However, I cannot do it right now, so please wait a little.
Thank you!

**Comment by kairi003** [comment]
I submitted the Firefox version to AMO!
If the review is completed without any issues, it should be published :)
https://addons.mozilla.org/ja/firefox/addon/get-cookies-txt-locally/

**Comment by pzhlkj6612** [comment]
[privacy-policy.md](https://github.com/kairi003/Get-cookies.txt-LOCALLY/blob/50590cad975ab49ff6dbc42ed735cedee088667d/privacy-policy.md) and [privacy-policy.jp.md](https://github.com/kairi003/Get-cookies.txt-LOCALLY/blob/50590cad975ab49ff6dbc42ed735cedee088667d/privacy-policy.jp.md) may also need to be updated (with content about Firefox)?

**Comment by kairi003** [comment]
Thank you for pointing this out! I'll take care of it.
