### ISSUE TITLE
README: add content about acquired permissions

### ISSUE THREAD

**Issue by pzhlkj6612** [kairi003/Get-cookies.txt-LOCALLY#27]
Hello!

0ad7c6788ae8da76fc7e0f831945508c8b759f53 introduced the new permission "downloads" and this will make Google Chrome say:

> ... "Get cookies.txt LOCALLY" has been disabled because it requires more permissions:
> 
> It can now:
> Manage your downloads

To avoid surprising users, I think it would be better if you add some explanation about the permissions this extension is using to README.

**Comment by kairi003** [comment]
Thanks for Issue, I have updated the README and store page!
