### ISSUE TITLE
How can I import cookies exported by this tool into other browsers？

### ISSUE THREAD

**Issue by yizhimengxin2233** [kairi003/Get-cookies.txt-LOCALLY#38]
I exported the cookie using this tool, but I can't find any way to import this cookie file into other browsers (I thought it was a tool for backup), so how can I import it into the browser?
（translated by Google)

**Comment by kairi003** [comment]
Thank you for your issue.

This extension is intended to export cookies, not backup them.
That is, it assists in loading browser cookies with other applications (e.g., curl, python, and so on).

Cookie import functionality could be added in the future, but it is a dangerous operation that destroys the security and integrity of a website so I think it should be done with caution.
