### ISSUE TITLE
How can i import that cookies file in to chrome again for future use?

### ISSUE THREAD

**Issue by RoopakShukla** [kairi003/Get-cookies.txt-LOCALLY#39]
I use Incog mode only, and as you know cookies get deleted automatically if you close all incognito tabs/windows so is there a way I can import my cookies file back again just in case I close them by mistake or have to restart my laptop, etc?

**Comment by kairi003** [comment]
This is an extension to export cookies.txt, so we do not currently have an import function.
I know that it is wanted, but I believe I should be cautious about adding it, as overwriting cookies is a very dangerous practice for users who do not have sufficient knowledge.
In the future, I would add it as an optional feature with a stern warning, or create it as the independent extension.

ref: https://github.com/kairi003/Get-cookies.txt-LOCALLY/issues/38
