### ISSUE TITLE
2 TAB issue

### ISSUE THREAD

**Issue by nextquick** [kairi003/Get-cookies.txt-LOCALLY#4]
Sometimes fields are separated with two TAB instead of one. Please see attached capture.

BTW, an idea: old "get cookies.txt" extension (not yours, I know!) had a counter on the icon, was quite handy...

Nice extension, thanks!
![get_cookies_issue](https://user-images.githubusercontent.com/34902139/223730321-8a8f8831-06ca-4663-8748-d8a933087900.jpg)

**Comment by nextquick** [comment]
Ok, the issue is not the 2 tabs but a missing "0" between them. Thanks

**Comment by kairi003** [comment]
I'll add Counter in the future, thanks!

**Comment by kairi003** [comment]
Resolved by #5 #6
