### ISSUE TITLE
Icon badge count doesn't work correctly with multiple windows

### ISSUE THREAD

**Issue by adamtokyo** [kairi003/Get-cookies.txt-LOCALLY#49]
When there are multiple windows open, the icon badge text displays the same cookie count in all windows, instead of displaying the cookie count for the current tab in each window. I'm not sure if this is fixable, as the extension appears to be using `setBadgeText()` correctly according to the documentation.

**Comment by kairi003** [comment]
Thank you for your report and I fixed it!
Please wait for release :)
