### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by rakleed** [kairi003/Get-cookies.txt-LOCALLY#55]
At night or in dark rooms, it is frustrating to use the extension due to the bright white background. Please add a dark theme, and make the default sync the extension theme with the system theme.

More details: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by kairi003** [comment]
Now that I have some free time, I plan to work on it within this month.

**Comment by kairi003** [comment]
sorry, late noe
