### ISSUE TITLE
Not picking up cookies that have a partition key

### ISSUE THREAD

**Issue by RainerGevers** [kairi003/Get-cookies.txt-LOCALLY#57]
Good Day. It seems that cloudflare now tags their cookies with a partition key and these cookies no longer get picked up by the extention. Is there a way to fix this?

The toolbar widget shows (2) but when you click on it, it's empty.

Edit:
I believe this might be due to a API change from chrome. 
Alternatively it could be a bug in Chrome. I see this bug report that was apparently fixed in Feb, it might be a regression
https://issues.chromium.org/issues/323924496

I also believe this thread might have some valuable information
https://groups.google.com/a/chromium.org/g/chromium-extensions/c/Nh90FWSCong/m/MXzxU30fAAAJ

Chromium: Chromium: 124.0.6367.118 (Official Build) (64-bit)
Site: hiperdex.com
![image](https://github.com/kairi003/Get-cookies.txt-LOCALLY/assets/32453861/f93622c3-5e8b-40de-8a00-ac25587d2c13)
![image](https://github.com/kairi003/Get-cookies.txt-LOCALLY/assets/32453861/fbfcfc9b-9df6-40b1-881a-1a84d2b7d828)

**Comment by kairi003** [comment]
thanks for your report!
i'll check it on weekend.

**Comment by RainerGevers** [comment]
I have done some research and made some fixes that work on my machine. Please feel free to accept it or maybe use it to guide a better solution

https://github.com/kairi003/Get-cookies.txt-LOCALLY/pull/58
