### ISSUE TITLE
On click permissions don't work

### ISSUE THREAD

**Issue by trick2011** [kairi003/Get-cookies.txt-LOCALLY#73]
The extensions doesn't work when I enable 'On click' site access. The elements field doesn't get filled after clicking. It does work when I set it one level up, to:  'On specific sites'.

Chome Version 125.0.6422.141 (Official Build) (64-bit) on Linux

**Comment by kairi003** [comment]
Yes, and this is a specification of Chrome.

The chrome.cookies API does not work with 'On click' permissions.

You need permission for a specific host to run this API.

I too would have preferred to have cookies referenced only on click, but that doesn't seem to be possible.

**Comment by trick2011** [comment]
Well, that sucks but at least thanks for the fast and clear answer.
